export const RECIPE_RANDOM_REQUEST = 'RECIPE_RANDOM_REQUEST'
export const RECIPE_RANDOM_SUCCESS = 'RECIPE_RANDOM_SUCCESS'
export const RECIPE_RANDOM_FAIL = 'RECIPE_RANDOM_FAIL'

export const RECIPE_SEARCH_REQUEST = 'RECIPE_SEARCH_REQUEST'
export const RECIPE_SEARCH_SUCCESS = 'RECIPE_SEARCH_SUCCESS'
export const RECIPE_SEARCH_FAIL = 'RECIPE_SEARCH_FAIL'

